name: Weekly Scraping Fall-Winter Current Year

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl google-chrome-stable
          # No need to download Chrome deb package separately, just install google-chrome-stable

          # Install Python dependencies
          pip install -r requirements.txt

      - name: Write Firebase Credentials File
        run: echo "$FIREBASE_SERVICE_ACCOUNT" > serviceAccountKey.json
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Run scraping script
        run: python scraper_multithreaded_fall_winter.py